Repository Byzanteam/workflow_metal, pull requests merged in 2020-07, with the labels that each got.

#43 增加 create_case api
  lib/workflow_metal/application.ex
Labels: Ready to review

#44 增加 open_case api
  lib/workflow_metal/application.ex
Labels: Ready to review

#47 feat: remove guard
  lib/workflow_metal/application/workflows_supervisor.ex
  lib/workflow_metal/storage/schema/arc.ex
  lib/workflow_metal/storage/schema/guard.ex
Labels: ✨feature

#48 refactor: typespec
  .formatter.exs
  .github/workflows/main.yml
  lib/workflow_metal/case/case.ex
  lib/workflow_metal/storage/adapters/in_memory.ex
  lib/workflow_metal/storage/schema/arc.ex
  lib/workflow_metal/storage/schema/case.ex
  lib/workflow_metal/storage/schema/place.ex
  lib/workflow_metal/storage/schema/task.ex
  lib/workflow_metal/storage/schema/token.ex
  lib/workflow_metal/storage/schema/transition.ex
  lib/workflow_metal/storage/schema/workflow.ex
  lib/workflow_metal/storage/schema/workitem.ex
  lib/workflow_metal/task/task.ex
  lib/workflow_metal/workitem/workitem.ex
  mix.exs
  mix.lock
Labels: Ready to review, enhancement
